export const CALCULATE_AVAILABLE_EXAMINERS = 'CALCULATE_AVAILABLE_EXAMINERS';
export const FILTER_EXAMINERS = 'FILTER_EXAMINERS';
export const FILTER_SUPPORT = 'FILTER_SUPPORT';
export const SELECT_EXAMINER = 'SELECT_EXAMINER';
export const CLEAR_SELECTED_EXAMINERS = 'CLEAR_SELECTED_EXAMINERS'