export const CALCULATE_AVAILABLE_EXAMINERS = 'CALCULATE_AVAILABLE_EXAMINERS';
export const CALCULATE_AVAILABLE_EXAMINERS_ON_CHANGE = 'CALCULATE_AVAILABLE_EXAMINERS_ON_CHANGE';
export const CALCULATE_SAME_DAY_SESSIONS = 'CALCULATE_SAME_DAY_SESSIONS';