export const LOAD_EXAMINERS_SUCCESS = 'LOAD_EXAMINERS_SUCCESS';
export const ADD_EXAMINER_SUCCESS = 'ADD_EXAMINER_SUCCESS';
export const DELETE_EXAMINER_SUCCESS = 'DELETE_EXAMINER_SUCCESS';
export const FAILED_LOAD = 'FAILED_LOAD';
export const FETCH_EXAMINER_FOR_EDITING = 'FETCH_EXAMINER_FOR_EDITING';
export const UPDATE_EXAMINER_SUCCESS = 'UPDATE_EXAMINER_SUCCESS';
export const DEACTIVATE_SELECTED_EXAMINER = 'DEACTIVATE_SELECTED_EXAMINER';