export const LOAD_EXAMINERS_SUCCESS = 'LOAD_EXAMINERS_SUCCESS';
export const ADD_EXAMINER_SUCCESS = 'ADD_EXAMINER_SUCCESS';
export const DELETE_EXAMINER_SUCCESS = 'DELETE_EXAMINER_SUCCESS';
export const FAILED_LOAD = 'FAILED_LOAD';
export const FETCH_EXAMINER = 'FETCH_EXAMINER';
export const UPDATE_EXAMINER_SUCCESS = 'UPDATE_EXAMINER_SUCCESS';
export const DEACTIVATE_SELECTED_EXAMINER = 'DEACTIVATE_SELECTED_EXAMINER';

export const INITIALISE_LOGIN = 'INITIALISE_LOGIN';

export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS';
export const ADD_SESSION_SUCCESS = 'ADD_SESSION_SUCCESS';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const FETCH_SESSION = 'FETCH_SESSION';
export const DEACTIVATE_SELECTED_SESSION = 'DEACTIVATE_SELECTED_SESSION';
export const FILTER_SESSIONS = 'FILTER_SESSIONS';

export const LOAD_PERIODS = 'LOAD_PERIODS';
export const UPDATE_PERIODS = 'UPDATE_PERIODS';
export const SET_PERIOD = 'SET_PERIOD';

export const LOG_RESPONSE = 'LOG_RESPONSE';