export const LOAD_EXAMINERS_SUCCESS = 'LOAD_EXAMINERS_SUCCESS';
export const ADD_EXAMINER_SUCCESS = 'ADD_EXAMINER_SUCCESS';
export const DELETE_EXAMINER_SUCCESS = 'DELETE_EXAMINER_SUCCESS';
export const FAILED_LOAD = 'FAILED_LOAD';
export const FETCH_EXAMINER = 'FETCH_EXAMINER';
export const UPDATE_EXAMINER_SUCCESS = 'UPDATE_EXAMINER_SUCCESS';
export const UPDATE_EXAMINER_FAIL = 'UPDATE_EXAMINER_SUCCESS';
export const DEACTIVATE_SELECTED_EXAMINER = 'DEACTIVATE_SELECTED_EXAMINER';

export const REGISTER_EXAMINER_START = 'REGISTER_EXAMINER__START';
export const REGISTER_EXAMINER_SUCCESS = 'REGISTER_EXAMINER__SUCCESS';
export const REGISTER_EXAMINER_FAIL = 'REGISTER_EXAMINER__FAIL';

export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const INITIALISE_LOGIN = 'INITIALISE_LOGIN';

export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS';
export const ADD_SESSION_SUCCESS = 'ADD_SESSION_SUCCESS';
export const ADD_SESSION_FAIL = 'ADD_SESSION_FAIL';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const UPDATE_SESSION_FAIL = 'UPDATE_SESSION_FAIL';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const FETCH_SESSION = 'FETCH_SESSION';
export const DEACTIVATE_SELECTED_SESSION = 'DEACTIVATE_SELECTED_SESSION';
export const FILTER_SESSIONS = 'FILTER_SESSIONS';

export const LOAD_PERIODS = 'LOAD_PERIODS';
export const UPDATE_PERIODS = 'UPDATE_PERIODS';
export const HANDLE_PERIOD_SELECT = 'HANDLE_PERIOD_SELECT';

export const LOG_RESPONSE = 'LOG_RESPONSE';
export const LOG_ERROR = 'LOG_ERROR';
export const REFRESH_LOG = 'REFRESH_LOG';