export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_REGULAR_USER = 'AUTH_ REGULAR_USER';
export const AUTH_REGULAR_USER_SUCCESS = 'AUTH_REGULAR_USER_SUCCESS';
export const AUTH_REGULAR_USER_FAIL = 'AUTH_REGULAR_USER_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';