export const LOAD_PERIODS = 'LOAD_PERIODS';
export const UPDATE_PERIODS = 'UPDATE_PERIODS';
export const HANDLE_PERIOD_SELECT = 'HANDLE_PERIOD_SELECT';
export const HANDLE_PERIOD_SELECT_WEEK = 'HANDLE_PERIOD_SELECT_WEEK';