export const ADD_VENUE_SUCCESS = 'ADD_VENUE_SUCCESS';
export const LOAD_VENUE_SUCCESS = 'LOAD_VENUE_SUCCESS';
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS';
export const UPDATE_VENUE_SUCCESS = 'UPDATE_VENUE_SUCCESS';
export const FETCH_VENUE = 'FETCH_VENUE';
export const CLEAR_SELECTED_VENUE = 'CLEAR_SELECTED_VENUE';