export const ADD_VENUE_SUCCESS = 'ADD_VENUE_SUCCESS';
export const LOAD_VENUE_SUCCESS = 'LOAD_VENUE_SUCCESS';
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS';
export const FETCH_VENUE = 'FETCH_VENUE';